### ISSUE TITLE
can you run this on a mac?

### ISSUE THREAD

**Issue by LeoMehraban** [Hadeweka/Inuhh-Shinvasion#2]
if not, can you please tell me. it looks amazing but i have a mac.

**Comment by Hadeweka** [comment]
Since I have no Mac, I have no way of testing it, but _technically_ it should work.

You'd need to make sure SDL, Ruby and Gosu are all properly installed.
In the **Prerequisites** section on https://github.com/gosu/gosu/wiki/Getting-Started-on-OS-X there is a short guide on how to do this. 

To start the game, just run `ruby Inuhh.rb` afterwards.

I'd appreciate if you could test it and provide an update on whether it worked or not.

**Comment by Hadeweka** [comment]
I will close this for now, since there hasn't been any activity on this issue in the last years.

If there's any issue with running this on a Mac, this can be opened again, but I have not the ability to test this right now.
